# Generated by Django 4.2.29 on 2026-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isSaler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='storeName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
