# Generated by Django 4.2.29 on 2026-04-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_issaler_customuser_storename'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='goodsCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='storeName',
            field=models.CharField(max_length=100),
        ),
    ]
